### ISSUE TITLE
安装上之后编译报错

### ISSUE THREAD

**Issue by wjw2411** [qiyongzhong0/rt-thread-rs485#1]
rs485.c 第329行。
`
        int len = rt_device_read(hinst->serial, 0, buf + recv_len, size);
`
编译时报错，错误信息为：expression must be a pointer to a complete object type

查找后发现，buf是一个void *, 加上int型的recv_len就会报错
去掉 （+ recv_len）之后就能正常编译通过

**Comment by qiyongzhong0** [comment]
可能是有些编译器不支持void*类型指针的加减计算，你可以在buf前加上(char *)，明确下指针类型。修改后如下：
int len = rt_device_read(hinst->serial, 0, (char *)buf + recv_len, size);

 
发件人： wjw33
发送时间： 2020-12-11 14:24
收件人： qiyongzhong0/rt-thread-rs485
抄送： Subscribed
主题： [qiyongzhong0/rt-thread-rs485] 安装上之后编译报错 (#1)
rs485.c 第329行。
int len = rt_device_read(hinst->serial, 0, buf + recv_len, size);
编译时报错，错误信息为：expression must be a pointer to a complete object type
查找后发现，buf是一个void *, 加上int型的recv_len就会报错
去掉 （+ recv_len）之后就能正常编译通过

**Comment by qiyongzhong0** [comment]
fixed
